# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dI5qlQLwx8CJR-x40lNxWcP2jL2VMMsI
"""

import streamlit as st
from PIL import Image
import numpy as np
import tensorflow as tf
# Instead of importing from sklearn.externals, import directly from joblib
import joblib

# Load models and scaler
cnn_model = tf.keras.models.load_model('cnn_model.h5')
svm_model = joblib.load('svm_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("Diabetic Retinopathy Diagnosis")
st.write("Upload a retinal image for diagnosis")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file:
    image = Image.open(uploaded_file).resize((128, 128))
    image_array = np.array(image) / 255.0
    image_array = np.expand_dims(image_array, axis=0)

    # Predictions
    diagnosis = ensemble_predict(image_array, cnn_model, svm_model, scaler)

    # Display results
    st.write(f"Diagnosis: {diagnosis}")
    st.image(image, caption="Uploaded Retinal Image", use_column_width=True)